### ISSUE TITLE
Broken link that redirects to a nonexistent page

### ISSUE THREAD

**Issue by sctech-tr** [hacks-guide/Guide_Wii#107]
**Nintendo Wi-Fi Connection / Wiimmfi**

https://wii.hacks.guide/wiimmfi

**If you click on "If you want to see how to use the WiiWare Patcher, click here!" it redirects you to a nonexistent page.**

The page it tries to redirect you is https://wii.hacks.guide/wiiwarepatcher

**Comment by playerjmr** [comment]
fixed https://github.com/hacks-guide/Guide_Wii/commit/b0f51377651938af6b11d475a0b3c0353f9a393f
