### ISSUE TITLE
It should be made clear that BootMii should not be installed on the vWii (inside of a WiiU)

### ISSUE THREAD

**Issue by LucasMcToucas** [hacks-guide/Guide_Wii#111]
**Pages with issue(s)**
BootMii backup

https://wii.hacks.guide/bootmii
**Description of the issue(s)**
It should be made very clear that BootMii cannot and should not EVER be installed on a vWii (inside of a WiiU) as this could cause an unrecoverable brick, it would be a good idea to instead guide vWii/ WiiU users to https://wiiu.hacks.guide/#/ where they can learn to make a NAND dump of their WiiU's NAND, altough, if the WiiU is already modded, then this would have been done already.

**Comment by Naim2000** [comment]
I'm pretty sure the HackMii installer just won't let you install it

**Comment by playerjmr** [comment]
> I'm pretty sure the HackMii installer just won't let you install it

It’s true, I tested it
