### ISSUE TITLE
FAT32 reccomendation

### ISSUE THREAD

**Issue by OilFreak** [hacks-guide/Guide_Wii#54]
**Pages with issue(s)**
Wii guide FAQ
https://wii.hacks.guide/faq#storage-device-faq
**Description of the issue(s)**
The guide reccomends FAT32 as a file system, however FAT32 only supports files &le; 2GB. Users should be aware of this.
WiiFlow Lite supports NTFS file systems, and I'm not sure about USB Loader GX.

**Comment by playerjmr** [comment]
> FAT32 only supports files ≤ 2GB. Users should be aware of this.

* ≤ 4GB, and also there are programs capable for all platforms to be able to split Wii disk backups to fit on the drive with 100% support. 

Plus, other file systems such as NTFS and EXT are not maintained very well and have issues.
