### ISSUE TITLE
RiiTag "Instruction" button leads to a non-existent page

### ISSUE THREAD

**Issue by scudo005** [hacks-guide/Guide_Wii#66]
**Pages with issue(s)**

https://tag.rc24.xyz/

**Description of the issue(s)**

The "Instructions" buttons leads to [a page that doesn't exist anymore.](https://wii.guide/riitag)

**Comment by lifehackerhansol** [comment]
This is something for RC24 to fix; we decided to remove RiiTag as part of the migration (before the wii.guide redirects were planned). cc @noahpistilli 

We do have a backup of the old instructions [here](https://wiki.hacks.guide/wiki/RiiTag), whether RC24 wants it or not, but IMO RC24 should have their own guide.
