### ISSUE TITLE
Add a prebuilt `bootmii.ini`

### ISSUE THREAD

**Issue by lifehackerhansol** [hacks-guide/Guide_Wii#72]
**Pages with issue(s)**

bootmii

**Description of the issue(s)**

If BootMii is installed to boot2, by default it will load that on boot.

Nobody wants or cares for that, so perhaps we could consider shipping a prebuilt one to get around that fact. Theoretically it should not affect either IOS or boot2 to just ship one.

**Comment by playerjmr** [comment]
We could also just add instructions for people to autoboot to the system menu.

**Comment by lifehackerhansol** [comment]
We could. The thought for a prebuilt came up mainly because I didn't want to split instructions between IOS and boot2.

**Comment by playerjmr** [comment]
Shouldn’t need to split the instructions, just add a section for autobooting.

**Comment by playerjmr** [comment]
> **Pages with issue(s)**
> 
> bootmii
> 
> **Description of the issue(s)**
> 
> If BootMii is installed to boot2, by default it will load that on boot.
> 
> Nobody wants or cares for that, so perhaps we could consider shipping a prebuilt one to get around that fact. Theoretically it should not affect either IOS or boot2 to just ship one.

implemented https://github.com/hacks-guide/Guide_Wii/commit/2bbdda57c8a3430d8c7435b73b2e8009d46b2c0b
