### ISSUE TITLE
Add YouTube fixing guide for WiiMC

### ISSUE THREAD

**Issue by upintheairsheep** [hacks-guide/Guide_Wii#76]
Please add a guide to fix YouTube on WiiMC, as the official YouTube app was discontinued a long time ago.

https://tubefixer.ovh/wiimc.php
https://www.slickremix.com/docs/get-api-key-for-youtube/

**Comment by playerjmr** [comment]
If anything, would probably be a wiki page.

**Comment by larsenv** [comment]
@upintheairsheep WiiMC-SS on OSC has the fix included, TubeFixer does not work anymore, you have to use RiiTube

**Comment by playerjmr** [comment]
in that case I’ll fix the wiki to mention wiimc-ss instead of wiimc.
