### ISSUE TITLE
Installing forwarders

### ISSUE THREAD

**Issue by upintheairsheep** [hacks-guide/Guide_Wii#78]
Can you add a section to install forwarder WADs on a Wii, possibly using ~~removed~~ ? Please note that ~~removed~~ contains various untested WADs, and possibly dangerous, outdated WADs. https://www.gamebrew.org/wiki/Forwarder_Collection_Wii is another source for these.

**Comment by lifehackerhansol** [comment]
I don't agree with this being on the guide.

Try the wiki, minus the piracy site: https://wiki.hacks.guide

**Comment by upintheairsheep** [comment]
I was thinking that as well, to not include that cube site because clicking
the up directory leads to lots of pirated stuff, along with free stuff.
