### ISSUE TITLE
Add guide for GBA Link Cable Dumper

### ISSUE THREAD

**Issue by upintheairsheep** [hacks-guide/Guide_Wii#79]
Please create a page if in scope of this project (and not wiki-only) about [the GBA Link Cable Dumper](https://oscwii.org/library/app/gba-link-cable-dumper) homebrew app, which is a GameCube homebrew that works on the Wii like most GC homebrew, but you need a Game Boy Advance Link Cable, the GBA itself, and a GameCube controller, and a GBA game optionally, the tool dumps the game, the save, and the GBA BIOS. Can be used to legally obtain the ROMs and BIOS of Game Boy games, as well as to dump the save file. The files can be played on the Wii via an emulator, via a GBA/DS flashcart, installed on the 3DS, or emulated on a PC via an emulator.

Otherwise add this to the recommended homebrew section.

**Comment by playerjmr** [comment]
Not adding this to the guide for a few reasons:

1. it’s pretty self explanatory. You press a button to dump the bios then press a different button to dump a game or save.
2. It’s not a very commonly requested thing. Hardly anyone even owns a GBA link cable.
3. Dumping GBA games through the link cable is extremely slow. You’re better off either buying a GameCube with the gameboy player attachment or a DS with a GBA cartridge slot. 

I would be fine with it being a wiki page, but it certainly does not belong on the main guide.

**Comment by upintheairsheep** [comment]
> Not adding this to the guide for a few reasons:
> 
> 1. it’s pretty self explanatory. You press a button to dump the bios then press a different button to dump a game or save.
> 2. It’s not a very commonly requested thing. Hardly anyone even owns a GBA link cable.
> 3. Dumping GBA games through the link cable is extremely slow. You’re better off either buying a GameCube with the gameboy player attachment or a DS with a GBA cartridge slot.
> 
> I would be fine with it being a wiki page, but it certainly does not belong on the main guide.

Was just going to make this for the people who happened to own both, but at that point they likely own a DS already.

**Comment by playerjmr** [comment]
@upintheairsheep I made a wiki page regarding the use of the GBA link cable (I spent $20 to do it too). When it is approved it will be available at https://wiki.hacks.guide/wiki/Wii:GBA_Link_Cable_Usage

**Comment by upintheairsheep** [comment]
You can sell it for 20 or 21 or more dollars now.
